// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) 
FROM users_schema.users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
WITH new_user AS (
    INSERT INTO users_schema.users (id, username)
    VALUES (
        $1, 
        $2
    )
    RETURNING id, username, score, created_at, updated_at
),
new_progress AS (
    INSERT INTO users_schema.user_progress (user_id)
    SELECT id FROM new_user
)
SELECT id, username, score, created_at, updated_at 
FROM new_user
`

type CreateUserParams struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
}

type CreateUserRow struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Score     int32              `json:"score"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT id, username, score
FROM users_schema.users
ORDER BY score DESC, id ASC
LIMIT $2 OFFSET $1
`

type GetLeaderboardParams struct {
	Offs int32 `json:"offs"`
	Lim  int32 `json:"lim"`
}

type GetLeaderboardRow struct {
	ID       int64  `json:"id"`
	Username string `json:"username"`
	Score    int32  `json:"score"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, arg.Offs, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(&i.ID, &i.Username, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, score, created_at, updated_at
FROM users_schema.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (UsersSchemaUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i UsersSchemaUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Score,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserProgress = `-- name: GetUserProgress :one
SELECT user_id, scenarios_completed, scams_detected, failed_attempts, updated_at
FROM users_schema.user_progress
WHERE user_id = $1
`

func (q *Queries) GetUserProgress(ctx context.Context, userID int64) (UsersSchemaUserProgress, error) {
	row := q.db.QueryRow(ctx, getUserProgress, userID)
	var i UsersSchemaUserProgress
	err := row.Scan(
		&i.UserID,
		&i.ScenariosCompleted,
		&i.ScamsDetected,
		&i.FailedAttempts,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserScore = `-- name: UpdateUserScore :one
UPDATE users_schema.users
SET score = score + $1
WHERE id = $2
RETURNING id
`

type UpdateUserScoreParams struct {
	ScoreDelta int32 `json:"score_delta"`
	ID         int64 `json:"id"`
}

func (q *Queries) UpdateUserScore(ctx context.Context, arg UpdateUserScoreParams) (int64, error) {
	row := q.db.QueryRow(ctx, updateUserScore, arg.ScoreDelta, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
