// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"
)

type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, username string) (CreateUserRow, error)
	GetLeaderboard(ctx context.Context, arg GetLeaderboardParams) ([]GetLeaderboardRow, error)
	GetUserByID(ctx context.Context, id int64) (UsersSchemaUser, error)
	GetUserProgress(ctx context.Context, userID int64) (UsersSchemaUserProgress, error)
	UpdateUserScore(ctx context.Context, arg UpdateUserScoreParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
