// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package chatsqlc

import (
	"time"
)

type Chat struct {
	ID         int64      `json:"id"`
	UserID     int64      `json:"user_id"`
	ScenarioID int64      `json:"scenario_id"`
	Title      string     `json:"title"`
	Status     string     `json:"status"`
	Resume     string     `json:"resume"`
	Score      int64      `json:"score"`
	CreatedAt  time.Time  `json:"created_at"`
	FinishedAt *time.Time `json:"finished_at"`
}

type Incident struct {
	ID        int64     `json:"id"`
	ChatID    int64     `json:"chat_id"`
	Type      string    `json:"type"`
	Comment   string    `json:"comment"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID         int64     `json:"id"`
	ChatID     int64     `json:"chat_id"`
	SenderType string    `json:"sender_type"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
}
