// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package chatsqlc

import (
	"context"
	"time"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (user_id, scenario_id, session_id, title, status, resume, score, current_node_id, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id
`

type CreateChatParams struct {
	UserID        int64     `json:"user_id"`
	ScenarioID    int64     `json:"scenario_id"`
	SessionID     string    `json:"session_id"`
	Title         string    `json:"title"`
	Status        string    `json:"status"`
	Resume        string    `json:"resume"`
	Score         int64     `json:"score"`
	CurrentNodeID string    `json:"current_node_id"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (int64, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.UserID,
		arg.ScenarioID,
		arg.SessionID,
		arg.Title,
		arg.Status,
		arg.Resume,
		arg.Score,
		arg.CurrentNodeID,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDecision = `-- name: CreateDecision :one
WITH new_decision AS (
    INSERT INTO chat_decisions (chat_id, node_id, transition_id, target_node_id, score_delta, feedback)
    VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
    RETURNING id, created_at
), updated_chat AS (
    UPDATE chats
    SET score = $7,
        current_node_id = $4
    WHERE id = $1
)
SELECT id, created_at
FROM new_decision
`

type CreateDecisionParams struct {
	ChatID       int64  `json:"chat_id"`
	NodeID       string `json:"node_id"`
	TransitionID string `json:"transition_id"`
	TargetNodeID string `json:"target_node_id"`
	ScoreDelta   int64  `json:"score_delta"`
	Feedback     string `json:"feedback"`
	Score        int64  `json:"score"`
}

type CreateDecisionRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (CreateDecisionRow, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ChatID,
		arg.NodeID,
		arg.TransitionID,
		arg.TargetNodeID,
		arg.ScoreDelta,
		arg.Feedback,
		arg.Score,
	)
	var i CreateDecisionRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_type, content)
VALUES ($1, $2, $3)
RETURNING id, created_at
`

type CreateMessageParams struct {
	ChatID     int64  `json:"chat_id"`
	SenderType string `json:"sender_type"`
	Content    string `json:"content"`
}

type CreateMessageRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.SenderType, arg.Content)
	var i CreateMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteChat = `-- name: DeleteChat :execrows
DELETE FROM chats
WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishChat = `-- name: FinishChat :execrows
UPDATE chats
SET status = $1,
    resume = $2,
    score = $3,
    finished_at = $4
WHERE id = $5
  AND status = 'active'
`

type FinishChatParams struct {
	Status     string     `json:"status"`
	Resume     string     `json:"resume"`
	Score      int64      `json:"score"`
	FinishedAt *time.Time `json:"finished_at"`
	ID         int64      `json:"id"`
}

// Завершение идемпотентно: параллельный ход агента не сможет завершить чат дважды.
func (q *Queries) FinishChat(ctx context.Context, arg FinishChatParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishChat,
		arg.Status,
		arg.Resume,
		arg.Score,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, user_id, scenario_id, session_id, title, status, resume, score, current_node_id, created_at, finished_at
FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScenarioID,
		&i.SessionID,
		&i.Title,
		&i.Status,
		&i.Resume,
		&i.Score,
		&i.CurrentNodeID,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listChatsByUserID = `-- name: ListChatsByUserID :many
SELECT id, user_id, scenario_id, session_id, title, status, resume, score, current_node_id, created_at, finished_at
FROM chats
WHERE user_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListChatsByUserIDParams struct {
	UserID  int64 `json:"user_id"`
	AfterID int64 `json:"after_id"`
	Lim     int32 `json:"lim"`
}

func (q *Queries) ListChatsByUserID(ctx context.Context, arg ListChatsByUserIDParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChatsByUserID, arg.UserID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScenarioID,
			&i.SessionID,
			&i.Title,
			&i.Status,
			&i.Resume,
			&i.Score,
			&i.CurrentNodeID,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByChatID = `-- name: ListDecisionsByChatID :many
SELECT id, chat_id, node_id, transition_id, target_node_id, score_delta, feedback, created_at
FROM chat_decisions
WHERE chat_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListDecisionsByChatIDParams struct {
	ChatID  int64 `json:"chat_id"`
	AfterID int64 `json:"after_id"`
	Lim     int32 `json:"lim"`
}

func (q *Queries) ListDecisionsByChatID(ctx context.Context, arg ListDecisionsByChatIDParams) ([]ChatDecision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByChatID, arg.ChatID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatDecision
	for rows.Next() {
		var i ChatDecision
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.NodeID,
			&i.TransitionID,
			&i.TargetNodeID,
			&i.ScoreDelta,
			&i.Feedback,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChatID = `-- name: ListMessagesByChatID :many
SELECT id, chat_id, sender_type, content, created_at
FROM messages
WHERE chat_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListMessagesByChatIDParams struct {
	ChatID  int64 `json:"chat_id"`
	AfterID int64 `json:"after_id"`
	Lim     int32 `json:"lim"`
}

func (q *Queries) ListMessagesByChatID(ctx context.Context, arg ListMessagesByChatIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByChatID, arg.ChatID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
