// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"time"
)

const createChat = `-- name: CreateChat :one
INSERT INTO chats (user_id, scenario_id, title, status, resume, score, created_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type CreateChatParams struct {
	UserID     int64     `json:"user_id"`
	ScenarioID int64     `json:"scenario_id"`
	Title      string    `json:"title"`
	Status     string    `json:"status"`
	Resume     string    `json:"resume"`
	Score      int64     `json:"score"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (int64, error) {
	row := q.db.QueryRow(ctx, createChat,
		arg.UserID,
		arg.ScenarioID,
		arg.Title,
		arg.Status,
		arg.Resume,
		arg.Score,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createIncident = `-- name: CreateIncident :one
WITH new_incident AS (
    INSERT INTO incidents (chat_id, type, comment)
    VALUES ($1, $2, $3)
    RETURNING id, created_at
), updated_chat AS (
    UPDATE chats
    SET score = $4
    WHERE id = $1
)
SELECT id, created_at
FROM new_incident
`

type CreateIncidentParams struct {
	ChatID  int64  `json:"chat_id"`
	Type    string `json:"type"`
	Comment string `json:"comment"`
	Score   int64  `json:"score"`
}

type CreateIncidentRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (CreateIncidentRow, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.ChatID,
		arg.Type,
		arg.Comment,
		arg.Score,
	)
	var i CreateIncidentRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id, sender_type, content)
VALUES ($1, $2, $3)
RETURNING id, created_at
`

type CreateMessageParams struct {
	ChatID     int64  `json:"chat_id"`
	SenderType string `json:"sender_type"`
	Content    string `json:"content"`
}

type CreateMessageRow struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.SenderType, arg.Content)
	var i CreateMessageRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const deleteChat = `-- name: DeleteChat :execrows
DELETE FROM chats
WHERE id = $1
`

func (q *Queries) DeleteChat(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChat, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChatByID = `-- name: GetChatByID :one
SELECT id, user_id, scenario_id, title, status, resume, score, created_at, finished_at
FROM chats
WHERE id = $1
`

func (q *Queries) GetChatByID(ctx context.Context, id int64) (Chat, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ScenarioID,
		&i.Title,
		&i.Status,
		&i.Resume,
		&i.Score,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listChatsByUserID = `-- name: ListChatsByUserID :many
SELECT id, user_id, scenario_id, title, status, resume, score, created_at, finished_at
FROM chats
WHERE user_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListChatsByUserIDParams struct {
	UserID  int64 `json:"user_id"`
	AfterID int64 `json:"after_id"`
	Lim     int32 `json:"lim"`
}

func (q *Queries) ListChatsByUserID(ctx context.Context, arg ListChatsByUserIDParams) ([]Chat, error) {
	rows, err := q.db.Query(ctx, listChatsByUserID, arg.UserID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chat
	for rows.Next() {
		var i Chat
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ScenarioID,
			&i.Title,
			&i.Status,
			&i.Resume,
			&i.Score,
			&i.CreatedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsByChatID = `-- name: ListIncidentsByChatID :many
SELECT id, chat_id, type, comment, created_at
FROM incidents
WHERE chat_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListIncidentsByChatIDParams struct {
	ChatID  int64 `json:"chat_id"`
	AfterID int64 `json:"after_id"`
	Lim     int32 `json:"lim"`
}

func (q *Queries) ListIncidentsByChatID(ctx context.Context, arg ListIncidentsByChatIDParams) ([]Incident, error) {
	rows, err := q.db.Query(ctx, listIncidentsByChatID, arg.ChatID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.Type,
			&i.Comment,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByChatID = `-- name: ListMessagesByChatID :many
SELECT id, chat_id, sender_type, content, created_at
FROM messages
WHERE chat_id = $1
  AND ($2::bigint = 0 OR id < $2::bigint)
ORDER BY id DESC
LIMIT $3
`

type ListMessagesByChatIDParams struct {
	ChatID  int64 `json:"chat_id"`
	AfterID int64 `json:"after_id"`
	Lim     int32 `json:"lim"`
}

func (q *Queries) ListMessagesByChatID(ctx context.Context, arg ListMessagesByChatIDParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByChatID, arg.ChatID, arg.AfterID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderType,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChat = `-- name: UpdateChat :execrows
UPDATE chats
SET title = $1,
    status = $2,
    resume = $3,
    score = $4,
    finished_at = $5
WHERE id = $6
`

type UpdateChatParams struct {
	Title      string     `json:"title"`
	Status     string     `json:"status"`
	Resume     string     `json:"resume"`
	Score      int64      `json:"score"`
	FinishedAt *time.Time `json:"finished_at"`
	ID         int64      `json:"id"`
}

func (q *Queries) UpdateChat(ctx context.Context, arg UpdateChatParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateChat,
		arg.Title,
		arg.Status,
		arg.Resume,
		arg.Score,
		arg.FinishedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
