// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package userssqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UsersSchemaUser struct {
	ID        int64              `json:"id"`
	Username  string             `json:"username"`
	Score     int32              `json:"score"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UsersSchemaUserProgress struct {
	UserID             int64              `json:"user_id"`
	ScenariosCompleted int32              `json:"scenarios_completed"`
	ScamsDetected      int32              `json:"scams_detected"`
	FailedAttempts     int32              `json:"failed_attempts"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
